### ISSUE TITLE
icon for metadata info panel

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#102]
We need a new icon for the new metadata info panel.

See #38 and #104

**Comment by frasercl** [comment]
Worth noting as well that we currently depend on some other icons from ant's library in production. Out of the full list [here](https://3x.ant.design/components/icon/), we use in rough order of prominence: `camera`, `setting`, `loading`, `step-backward`, `step-forward`, `down`. Some of these are prominent enough to deserve a custom design (`camera` is used in the screenshot button and lives in the toolbar alongside custom icons), others may be fine as is (`down` is the arrow in dropdowns and fits just fine with the rest of the icons in the app).

Additionally, our current antd version (v3) is all-or-nothing on icon loading: if you need one icon, your app builds with all of them. This is less an argument for making more of our own icons than it is for addressing #42.

**Comment by toloudis** [comment]
see #104 for reference

**Comment by thao-do** [comment]
Will attach final icons here after discussion to pick one. 

![Image](https://user-images.githubusercontent.com/25212364/223527618-b2b2aa8c-7c48-496d-a4cf-de78a1c7d4a2.png)

**Comment by frasercl** [comment]
![image](https://user-images.githubusercontent.com/53030214/230964737-2e4e170b-8e7e-41c4-8831-26fa63874c1a.png)
