### ISSUE TITLE
UX for metadata info panel

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#103]
We need to review the contents and organization of information for the new metadata info panel.
See #38 

Bear in mind the viewer will allow two sources for the data:  
(1) data sent in from the containing application: for example, measured features from CFE
(2) data that the viewer itself loads: for example, pixel dimensions or standard data embedded in the tiff image file from the microscope

At first I suggest three simple groupings for display:
Image Dimensions (source 2)
Image Metadata (source 2)
Measured Features (source 1, fed in from CFE)

**Comment by frasercl** [comment]
Screenshot for reference of the current look and capabilities of the prototype panel, though not necessarily its ideal organization.

![Image](https://user-images.githubusercontent.com/53030214/210440350-4373e1b5-d1b8-45dd-91ea-48455c64ae6a.png)

In the actual use Dan described, categories would all appear grouped at the top and contain no sub-categories, cutting down on visual clutter. Under the hood, users of this component could pass in boolean props to add or remove categories of information known to the viewer (source 2), along with their own metadata (with custom categories) to be displayed below those auto-generated categories (source 1, e.g. measured features from CFE).

**Comment by toloudis** [comment]
The capability to have arbitrary nesting (and therefore supporting arbitrary json objects?) is great to have even if we keep things relatively flat at first.

**Comment by lynwilhelm** [comment]
@frasercl as discussed in slack, here is my final design input. In the case of excessive nesting, the text will wrap when horizontal space gets too tight, making rows expand in height. Align font type, weights, colors for headings and body copy to the preexisting Channels Panel. Use same icon chevrons. Image here for reference. No borders on nested rows.

![Screenshot 2023-02-09 at 11 17 33 AM](https://user-images.githubusercontent.com/93954795/217923379-d31a77af-2c6c-427a-b886-e5bb3777b5ba.png)
