### ISSUE TITLE
toolbar buttons overlap when screen is not wide enough

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#105]
## Description

Some Buttons overlap when screen width is too small.  The buttons are harder to click.

## Expected Behavior

Toolbar buttons should always be available and clickable.

**Comment by toloudis** [comment]
<img width="158" alt="Screen Shot 2022-12-06 at 4 35 53 PM" src="https://user-images.githubusercontent.com/2193409/207437178-f3ea2fd7-033e-42cc-9c26-2b2dcb294679.png">

**Comment by toloudis** [comment]
@lynwilhelm Is the answer to this in the design spec?

**Comment by lynwilhelm** [comment]
![Screen Shot 2022-12-13 at 1 09 11 PM](https://user-images.githubusercontent.com/93954795/207444027-f7a63365-a622-4600-8c6e-c6d0a5b286b3.png)

Here is an example of my thinking for the time being: The pink is a left margin on the right aligned buttons. A better experience might be to switch to a bar/ribbon that the user can scroll right and left on to access the overflow buttons. Please reach out if you have alternate ideas!

**Comment by toloudis** [comment]
I like the idea of the scrollable ribbon that doesn't have to wrap and take up any more vertical space, while at the same time trying to make the buttons smaller (Icons for volumetric/maxproject/pathtrace and singlecell/fullfield).

I just took a look at Blender3d and that is exactly what they do!  As you narrow the view, toolbar buttons trail off the right edge and the whole button bar is horizontally scrollable.

I think our wrapping solution is probably much easier to implement(?) so I think we should at least do that for now.  But I really like having the toolbar stay the same vertical height.

**Comment by toloudis** [comment]
Another thing that could be nice is to replicate the toolbar in a control panel tab :wink:

**Comment by lynwilhelm** [comment]
@frasercl let us know your thoughts on our assumptions and if you agree that it's much easier to wrap for now rather than to try to implement a ribbon type solution. BUT if we want to really go for it now, I'm game.

**Comment by lynwilhelm** [comment]
Here is a design example (resting and hover)

![Screen Shot 2022-12-14 at 10 50 49 AM](https://user-images.githubusercontent.com/93954795/207686604-7ac274fe-bdb0-42fd-953b-388fcbaf5768.png)
![Screen Shot 2022-12-14 at 10 51 00 AM](https://user-images.githubusercontent.com/93954795/207686566-2a9973b3-bbde-46cd-b777-834bff109e78.png)

**Comment by frasercl** [comment]
It's definitely easier to wrap, but it might not be easier to polish the wrapping behavior enough that it looks good and works well. I definitely agree that scrolling is a better long-term solution, and I'd be inclined to pursue that, at least enough that it becomes obvious that it's tougher to do than we have time for now.

I've done a bit of experimentation under the (in retrospect, pretty wrong) assumption that only the centered elements would scroll, and found that it definitely is too tough to get the buttons to center within the viewport but scroll within the asymmetric space between the left- and right-aligned buttons. But it shouldn't be too difficult to collapse all elements to the left when screen space gets too small and scroll from there.

**Comment by lynwilhelm** [comment]
Awesome. Keep me updated. I just realized a left-aligned box and arrow would appear the moment the user scrolls to the right. I also assume the user could hover and/or click and it would scroll. There are some accessibility things to be aware of as well. One operating with keys only should be able to access buttons at all times. Without dedicating time, I can't immediately think through everything but I'm ok using best judgement for now and revisiting later if need be:)
