### ISSUE TITLE
Shareable links

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#107]
### Background

Users want to be able to share visualizations.  The viewer has lots of settings where users can customize the appearance of their data.   

### User needs statement(s)
As a user, I want to communicate a visualization that I have generated, to my colleagues.
As a user, I want to generate a link that I can send to someone else, and they will see what I see.

### Size
sm

### Requirements
User has a way to share their visualization with another user, so that the second user can open it seamlessly with the same settings.

### Deliverables
High fidelity design for generating and sharing the visualization

### Stakeholder(s)
@frasercl @toloudis

### Timeline
TBD; this is a high impact feature for our users but delivery is not time sensitive

### Notes
- We expect that a single url will not capture all the settings.
- A file is a natural way to store these settings

**Comment by toloudis** [comment]
see #97

**Comment by toloudis** [comment]
Adding another requirement from users:  if we generate a json file, they may make many copies of it and both manually and programmatically edit the files, and host them so they can be accessed via url.

**Comment by toloudis** [comment]
"Share" Button in UI
can we do this so that users don't have to save separate files? do we have any chance of compressing all of it into the url for real

**Comment by toloudis** [comment]
Share button could have one option for generating a URL and another option for saving a json.  UI then needs a way to load a json in addition to "share/saving" one.

**Comment by lynwilhelm** [comment]
@toloudis Is this the developer implementation ticket? If so, I will remove it being sent to my ux tracking project. I like that UX tickets exist separate from an implementation ticket though.

**Comment by toloudis** [comment]
Yes this one is for implementation now, because #171 exists
