### ISSUE TITLE
publish stable build in addition to nightly

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#116]
## Use Case

External users would like a public url to access the standalone viewer.  However, the current public url is a nightly build which may be unstable from day to day.

## Solution

In addition to publishing a nightly, which is useful, we should also publish the latest versioned release to a public url, which we would consider "stable".

**Comment by frasercl** [comment]
**allen-cell-animated.github.io/website-3d-cell-viewer** should link to the latest versioned and published version of the viewer.

**allen-cell-animated.github.io/website-3d-cell-viewer/nightly** should link to the most recent commit on main.

Nice to have:
- a way to use the latest main of volume-viewer with the latest main of website-3d-cell-viewer
- a way to deploy specific branches before merging to main

**Comment by toloudis** [comment]
Example of gh-action that presents user interface options:
https://github.com/allen-cell-animated/cell-feature-data/blob/main/.github/workflows/upload-dataset.yml
(see `on: workflow-dispatch: inputs`)

**Comment by toloudis** [comment]
Example of nightly dev and nightly release builds in simularium:
https://github.com/simularium/simularium-website/blob/main/.github/workflows/nightly-new-viewer.yml
This solution used a completely separate s3 bucket to deploy the builds.  I still think it can be done with gh-pages with a sufficiently advanced action that suports gh-pages subdirectories.
