### ISSUE TITLE
idea for redoing the transfer function editor

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#131]
### Background
#79 
We have per-channel controls that may be excessively complicated for our users.  

### User needs statement(s)
As a microscopist or cell biologist who needs to inspect raw images, I need quick and easy contrast adjustment controls.

### Size
m

### Requirements
I have a specific idea in mind that I want to put down in writing here.
User research has shown that users typically only need to set the "min" and "max" for intensity remapping and rarely (possibly never) will need anything more complicated.  I propose making the histogram control smaller and simpler:
* always only 2 control points showing and users can move only those points. 
* (perhaps an "advanced" mode where user can add control points?  not sure if needed)
* add a menu of color maps, and the ability to create a custom color map.  The color map would be applied between max and min.  A color map is basically just a color gradient. (example: https://docs.paraview.org/en/v5.10.0/_images/ColorMapComboBox.png)
* we still want to preserve "colorize" mode but this might be achievable with just a color map.
* does applying a color map override the single-color per channel?  currently this is used as a multiplier, with an alpha slider to control how much it contributes

### Deliverables
TBD

### Stakeholder(s)
@toloudis @frasercl @lynwilhelm (should add at least one imaging user)

### Timeline
TBD

**Comment by frasercl** [comment]
Captured by/included in #80 - resolve when it resolves

**Comment by frasercl** [comment]
@toloudis confirming: #294 resolves this? There's at least one feature idea here (a color map menu) that isn't included in that.

**Comment by toloudis** [comment]
> @toloudis confirming: #294 resolves this? There's at least one feature idea here (a color map menu) that isn't included in that.

Yes, we can just call this completed.  My intention was to somehow preserve an "easy" way to make a color gradient from min to max.  We can make a new "idea/suggestion" ticket for it or something

**Comment by frasercl** [comment]
Remaining unimplemented suggestion captured in #315. Closing this now.
