### ISSUE TITLE
Play controls for time slider in XY Mode

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/website-3d-cell-viewer#163]
## Use Case

Allow users to start playback in XY Mode

## Solution

- Imitate the Z-slider playback controls

**Comment by toloudis** [comment]
Z already has play controls.  Need to determine user interaction (disable etc)

**Comment by toloudis** [comment]
We want the same type of control that's in Z (play/pause).   Just need to account for user flow details like what needs to be disabled etc.

**Comment by lynwilhelm** [comment]
Dan and I discussed the following design approach today, so we can move forward with implementation. (See image for reference) Please reach out with any new issues or questions that require UX input! 

Acceptance criteria:
- Add play/pause button to Time slider row in
- Prevent user from interacting with anything in the Z slider row when user is actively playing through Time
- Prevent user from interacting with anything in Time slider row when user is actively playing through Z slider slices
- Add .5 (50%) opacity to slider controls (not the labels) when disabled
- Set cursor:not-allowed; css property for when user hovers over disabled area

When 
![Screenshot 2023-07-06 at 11 19 00 AM](https://github.com/allen-cell-animated/website-3d-cell-viewer/assets/93954795/29a16e24-8fb6-45c6-a4eb-9bc29c05349b)
