### ISSUE TITLE
Dockerfile is out of date

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#169]
## Description

Our Dockerfile does not build because it's so old and depends on old infrastructure.

## Expected Behavior

A very simple dockerfile that can copy the source code in, run npm build, and serve up the dist/ directory over http

## Reproduction

try building the dockerfile!

**Comment by frasercl** [comment]
@amilworks has written a dockerfile for this viewer before - can we take it?
