### ISSUE TITLE
shareable links ux design

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#171]
see #107 

roughly: share to json or long url, buttons for save json or load json
Maybe a "Share" button which is a metaphor most users are familiar with.

**Comment by lynwilhelm** [comment]
@toloudis Should we just delete this issue? Seems like a duplicate. Or, is #107 the dev implementation specific ticket? If so, I can just remove #107 ux backlog and tracking project designation.

**Comment by lynwilhelm** [comment]
@toloudis @TravisKroeker This seems like it should be assigned to me since I'm currently working on the public header. I'll change to me.

**Comment by lynwilhelm** [comment]
@toloudis @frasercl Should I work on this ticket (corresponding implementation ticket)?

**Comment by toloudis** [comment]
Yes please, although it might be kind of trivial, it could also fold in with a more general "Load" dialog.
@frasercl do we need to discuss whether URLs will have complete settings inline?  Currently the URL does allow a few key settings to be specified, like channels enabled, channel colors, and a simplified channel thresholding

**Comment by frasercl** [comment]
I was under the impression we did want to move towards all (or most) settings in the URL, though whether it should auto-update the URL for the user's copy-and-paste convenience or whether a complete settings URL should have to be produced with a button might be a discussion.
