### ISSUE TITLE
Support of OME-NGFF images without Z or T dimension

### ISSUE THREAD

**Issue by berombau** [allen-cell-animated/website-3d-cell-viewer#172]
## Use Case

OME-NGFF images can currently be viewed, but only if they have Z and/or T dimensions.
[viewing 10501752.zarr does not work](https://allen-cell-animated.github.io/website-3d-cell-viewer/?url=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0076A/10501752.zarr) 
[viewing 5025553.zarr works](https://allen-cell-animated.github.io/website-3d-cell-viewer/?url=https://uk1s3.embassy.ebi.ac.uk/idr/zarr/v0.4/idr0054A/5025553.zarr) (although XY view instead of 3D view does not work either)

[list of OME-NGFF samples](https://idr.github.io/ome-ngff-samples/)
```
0.4 	10501752.zarr 464 	494 		50 		XYC 			
0.4 	5025553.zarr 2500 	2500 	1 	27 	1 	XYZCT 	
```
## Solution

XYC datasets are opened in a working XY view or XYC datasets are changed to XYZCT datasets by the viewer automatically.

## Alternatives

Adding dummy Z=1 and T=1 dimensions when creating the datasets is possible, but not practical for users.

**Comment by toloudis** [comment]
Thank you for reporting this. I'm going to look into it today and see if I can get it fixed quickly.  I believe we do have an implicit assumption of at least XYZ dims but I'm sure we can implement some form of your suggested solution to all these to load properly.
