### ISSUE TITLE
info panel accordion collapse behavior broken on safari

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#176]
## Description

The collapsible sections don't collapse on Safari

<img width="477" alt="287085340-f2645a23-20ac-46e4-a9d7-0e717abcf0b7" src="https://github.com/allen-cell-animated/website-3d-cell-viewer/assets/2193409/5a8a514f-668b-45db-ae27-4b723f9d4278">

## Expected Behavior

should start out collapsed, and should open and close with the usual expand/collapse behavior.  This is functioning correctly on chrome and firefox.

## Reproduction

see above: simply use viewer in Safari.

## Environment

Safari safari safari

**Comment by frasercl** [comment]
Resolved, we think, by #177
