### ISSUE TITLE
landing page

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#188]
as designed.

Link to design:
https://www.figma.com/file/EJCCnElvRvObznBhN519sl/Components---CFE-%2B-3DWV?type=design&node-id=215%3A546&mode=design&t=L8nMtmh7C0xfVPfJ-1

**Comment by toloudis** [comment]
see if we can include opengraph tags

**Comment by lynwilhelm** [comment]
@ShrimpCryptid Link to designs added above

**Comment by ShrimpCryptid** [comment]
TODO thought dump of stuff that still needs to be done:
- [ ] Copy in the code from the colorizer
- [ ] Add styling variables to match with designs, and clean up/update the CSS variables already in the project
- [x] Add background video for the volume viewer.
  - [x] Host the video somewhere else, or in the project? (it's 15 MB...)
  - [x] Make it responsive to `prefers-reduced-motion`
- [ ] Update fonts to Helvetica + Open Sans to match the designs
- [ ] Loading volumes from landing page load buttons... discuss w/ Cameron how files should be loaded, will likely be affected by current PRs (https://github.com/allen-cell-animated/website-3d-cell-viewer/pull/207)
