### ISSUE TITLE
initial settings for nucmorph data

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#242]
Steps Matheus does when loading nucmorph images:
(Images are 2 channel raw (bright + egfp) and one channel Seg)

Turn off bright field
Switch to XY mode
In EGFP, click AutoIJ
In Segmentation, click Colorize

Simple implementation: allow colorize and any of the auto buttons (check new design for which auto buttons will still live)
Might have to allow specifying this by channel name string instead of channel index.  TODO: confirm whether the data is uniform in channel naming and ordering.

"Bright something?"
"EGFP"
"Channel:0:0"

**Comment by toloudis** [comment]
test url 
https://dev-aics-dtp-001.int.allencell.org/website-3d-cell-viewer/viewer?url=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2F%2Fassay-dev%2Fcomputational%2Fdata%2Frelease%2Fnuc-morph-data%2Fdata_for_analysis%2Fperturbations%2Fimportazole%2FLaminB1%2Fcontrol%2F20230417_01%2Fraw.ome.zarr%2Chttps%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2F%2Fassay-dev%2Fcomputational%2Fdata%2Frelease%2Fnuc-morph-data%2Fdata_for_analysis%2Fperturbations%2Fimportazole%2FLaminB1%2Fcontrol%2F20230417_01%2Fseg.ome.zarr

**Comment by ShrimpCryptid** [comment]
Closed by #253!
