### ISSUE TITLE
Import channels settings through URL parameters

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/website-3d-cell-viewer#249]
## Use Case
Preload certain settings per channel for sharing w/ default settings

## Solution

```
?url=url1,url2&enabledChannels=[1,2]&c0=[...]&c3=[...]
```
Major URL parameters:
- URLs, comma separated and encoded
- List of enabled channels
- For each channel, a parameter `c{n}` where `n` is the index of that channel, starting from 0.
  - Value is a comma separated, `key:value` list. (Can also try JSON.)
  - Keys correspond to values in `ChannelState`, copied below:
```
export interface ChannelState {
  name: string;
  volumeEnabled: boolean;
  isosurfaceEnabled: boolean;
  isovalue: number;
  colorizeEnabled: boolean;
  colorizeAlpha: number;
  opacity: number;
  color: ColorArray;
  controlPoints: ControlPoint[];
}
```

Also, all of the advanced render settings:
- Mask cell
- Brightness
- Density
- Levels (3 values)
- Interpolate (boolean)
- Background color
- Bounding box (boolean)
- Bounding box color

**Comment by ShrimpCryptid** [comment]
TODO: Split into 2+ smaller tickets

**Comment by ShrimpCryptid** [comment]
Questions:
- Does autoij actually take a second parameter? (from looking through code it doesn't seem to?)
-

**Comment by toloudis** [comment]
The regex in viewerchannelsetting is partially for the purpose of creating groupings of channels in the UI. (e.g. all channels starting with "SEG_" go under a section called "Segmentation")  I don't think we need that for the url parameters if it adds complexity.

**Comment by toloudis** [comment]
For autoij, I'm not sure what you mean by second parameter. If we have a min and max for each channel ,then we have to make a decision about how "autoij" should be encoded in that.  I was just thinking to keep it simple put autoij in either one or both and if it is found in either one, it could override.  This is also an opportunity to consider the naming of `autoij` with respect to #80

**Comment by toloudis** [comment]
see also #252 for additional functionality. Just linking to this issue.
