### ISSUE TITLE
Time slider does not update on playback

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/website-3d-cell-viewer#264]
## Description

_A clear description of the bug_

## Expected Behavior

_What did you expect to happen instead?_

## Reproduction

_A minimal example that exhibits the behavior._

## Environment

_Any additional information about your environment. E.g. OS version, python version, browser etc._

**Comment by toloudis** [comment]
Caused by changes in #256

**Comment by toloudis** [comment]
Z slider is also affected

**Comment by toloudis** [comment]
should AxisClipSliders use the new shared SliderRow component?
