### ISSUE TITLE
Add a button to show/hide the axis indicator

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#27]
## Use Case

volume-viewer supports hiding/showing an axis indicator in the corner of the display. But there is no control for it in the react front end.

## Solution

Add a button in the top set of controls before the Channels, on a new row

## Acceptance criteria

A button that toggles the axis indicators on the 3d canvas.
Button should say "Show Axes" when the axes are NOT visible, and "Hide Axes" when the axes ARE visible.

**Comment by toloudis** [comment]
I thought of one addition to this that I forgot to specify, which will probably be nice to have.
We would like to allow the viewer to be initialized with axes on or off, so:
* add a prop to the main app component with a boolean value so we can have it initialize to on or off.   
* you can test the prop in the public/index.jsx app by just hardcoding its value to true or false.
* the prop should be a child of the already existing `viewerConfig` prop

**Comment by frasercl** [comment]
Resolved by #29
