### ISSUE TITLE
switching from XY mode to 3D mode results in blank image

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#278]
## Description

When launching with new nucmorph data, we initialize to XY mode.   If you then switch to 3D mode the image is black/empty.  You can see on the Z slider that it is set to show only a single slice but the min and max are the same value.

## Expected Behavior

Switching to 3D mode should retain its own axis slider clipping settings and the first time you switch I would expect it to show the full 3D volume, if it hadn't been clipped in 3d mode before..

## Reproduction

https://volumeviewer.allencell.org/viewer?url=https%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc_morph_data%2Fdata_for_analysis%2Fbaseline_colonies%2F20200323_09_small%2Fraw.ome.zarr%2Chttps%3A%2F%2Fallencell.s3.amazonaws.com%2Faics%2Fnuc_morph_data%2Fdata_for_analysis%2Fbaseline_colonies%2F20200323_09_small%2Fseg.ome.zarr

wait for volume to load.  Then click on 3D button.

**Comment by ShrimpCryptid** [comment]
Fixed by #277!
