### ISSUE TITLE
add a show/hide bounding box button

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#28]
Use Case
volume-viewer supports hiding/showing a bounding box around the volume being displayed. But there is no control for it in the react front end.

Solution
Add a button in the top set of controls before the Channels, next to the hide/show axes button for now.  App component also has a prop so that bounding box can be initialized on or off when the volume is first loaded.

Acceptance criteria
A button that toggles the bounding box on the 3d canvas.
Button should say "Show Bounds" when the box is NOT visible, and "Hide Bounds" when the box IS visible.
App should be initializable with a boolean prop available/testable in the test app in the public/ directory.

**Comment by frasercl** [comment]
Resolved by #33

**Comment by frasercl** [comment]
Resolved by #33
