### ISSUE TITLE
Moving a control point causes other control point to jump

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#281]
## Description

when clicking to drag a control point, another control point will shift its position

## Expected Behavior

expect that moving a control point will not affect the displayed positions of any others

## Reproduction

https://dev-aics-dtp-001.int.allencell.org/website-3d-cell-viewer/viewer?url=https%3A%2F%2Fdev-aics-dtp-001.int.allencell.org%2F%2Fassay-dev%2Fcomputational%2Fdata%2Fholistic%2Fendos%2Ffeasibility%2Fcdh5.ome.zarr

go to frame 62.  
click IJ Auto
play a few frames until you see the right most control point move left so its x coordinate is less than 255.
pause
click the rightmost controlpoint to drag it and you will see the other control point jump to a different position.

## Environment
Windows, Chrome

**Comment by frasercl** [comment]
Resolved by #294
