### ISSUE TITLE
Save camera positioning + rotation to the URL

### ISSUE THREAD

**Issue by ShrimpCryptid** [allen-cell-animated/website-3d-cell-viewer#283]
## Use Case

_Please provide a use case to help us understand your request in context_

## Solution

_Please describe your ideal solution_

## Alternatives

_Please describe any alternatives you've considered, even if you've dismissed them_

**Comment by ShrimpCryptid** [comment]
Raises a question for me whether we should allow users to control how much information is saved in the URL...

**Comment by toloudis** [comment]
Basic requirement: if I give this url to someone else, they should see what I saw when I generated it.

**Comment by toloudis** [comment]
Note: are there any remaining settings that are NOT saved to the url?  Is there an image I can generate that isn't reproducible by shared url?

**Comment by ShrimpCryptid** [comment]
> Note: are there any remaining settings that are NOT saved to the url? Is there an image I can generate that isn't reproducible by shared url?

I think that'll only be possible if you enter the developer controls and make changes there.
