### ISSUE TITLE
Add a button to reset camera

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#30]
## Use Case

Users unfamiliar with 3d navigation by mouse in a 2d window can sometimes get lost, translate/zoom/rotate to a position that they can't get back from.   This is also a useful convenience even for users who are more experienced.

## Solution

A single command button to put the view back to its initial orientation

## Acceptance Criteria

A button called "Reset Camera" that resets the view to its initial orientation.  (I believe this functionality is already present in the viewer and just needs the button in the UI.). Button will eventually end up in our WIP toolbar design but for now should go above the Channels in the left hand panel.

**Comment by frasercl** [comment]
Resolved by #36
