### ISSUE TITLE
create toolbar component

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#37]
## Use Case

We want to move several of the buttons at the top of the control panel into a horizontal toolbar that can be placed at the top of the 3d canvas.

## Solution

- Create a React component that renders the complete set of buttons per @lynwilhelm design spec. 
- We can use placeholder icons for those buttons that require icons.
- Some buttons will need to convert from radio button groups to dropdowns.
- We want the toolbar to float over the 3d canvas (same relative "top")  but it should be its own component so that if we decided to, we could do layout such that it is vertically above the canvas.

## Design Specs
Follow specs in this design XD file for all styling guidance
https://xd.adobe.com/view/904d6444-a800-48b6-8844-4f6f116d85ab-c51e/

**Comment by toloudis** [comment]
TODO here: add links to design spec or snapshot images of it

**Comment by toloudis** [comment]
How should we proceed if ready to start coding but icons are not provided yet?  Wait, or start coding and use placeholders?  @lynwilhelm

**Comment by lynwilhelm** [comment]
> How should we proceed if ready to start coding but icons are not provided yet? Wait, or start coding and use placeholders? @lynwilhelm

Yep, placeholders for now if that's ok. @thao-do is working on them but not sure of her bandwidth. You can use the same icon for all of them if you want as we know what they are based on the placement.

**Comment by toloudis** [comment]
Thanks, placeholders is our preferred way to go, to allow dev to continue.  We can always add extra tasks etc for icon changes if they come in much later.
