### ISSUE TITLE
tabbed sections of user interface

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#70]
## Use Case

The tab to close the control panel pokes into the 3d view area intrusively.  We can redesign this to add a vertical strip to the left, put the open/close tab there, and this also provides a nice way to future-proof the ui for added functionality by allowing tabbed sections of controls.

## Solution

[Design spec link](https://xd.adobe.com/view/904d6444-a800-48b6-8844-4f6f116d85ab-c51e/)

**Comment by toloudis** [comment]
please fill in spec link but this is fully specified and ready for work.

**Comment by lynwilhelm** [comment]
Spec link provided above
