### ISSUE TITLE
masking behaves unintuitively with full field

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#88]
## Use Case

When user switches from single cell to full field, the cell mask alpha is still applied but the user does not expect the results they see.  
For example, why isn't only the single cell still masked?  
It is not clear to user that a named channel is being used as the mask in both cases.

## Solution

I think the viewer could have a "select mask channel name" in the UI and maybe an on/off switch in addition to the mask alpha value slider

**Comment by toloudis** [comment]
There's also the larger possibility of simply handling channels that we know are segmentations in a totally different way.  And providing more data to link the cell volume to the full field volume

**Comment by toloudis** [comment]
also see #99

**Comment by toloudis** [comment]
* when there is no mask channel found, the mask slider seems to mask out everything.  intuitively it maybe shouldnt mask anything?
*

**Comment by frasercl** [comment]
Does this require any design?

**Comment by toloudis** [comment]
* Just keep "mask alpha" the same across switching.
