### ISSUE TITLE
switching 3D to XY and back does not preserve mask alpha

### ISSUE THREAD

**Issue by toloudis** [allen-cell-animated/website-3d-cell-viewer#99]
## Description

Mask alpha value is being changed on me when I switch modes.

## Expected Behavior

Mask alpha should not change or at least change in a predictable and sensible way.

## Reproduction

Load viewer; mask alpha defaults to 50%.  
Set mask alpha to 100%.
Switch to XY mode.  Mask alpha moves to 0.
Switch back to 3D mode.  Mask alpha moves back to 50%!

**Comment by frasercl** [comment]
The viewer has been deliberately programmed this way, with constants `ALPHA_MASK_SLIDER_3D_DEFAULT` and `ALPHA_MASK_SLIDER_2D_DEFAULT`. It should be relatively trivial to remove this behavior, but it would be nice to settle on a sensible single default that makes sense in all render and view modes - e.g. Graham's suggestion of 85%.

Alternatively, the viewer could keep its defaults until the user deliberately interacts with the "mask cell" slider, at which point it would stop resetting and trust the user to set their own mask level.

**Comment by toloudis** [comment]
* Just don't change it across mode changes
